-- V1__init_app_info.sql

CREATE TABLE IF NOT EXISTS app_info (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_key   VARCHAR(100) NOT NULL UNIQUE,
    app_value VARCHAR(255) NOT NULL
);

INSERT INTO app_info (app_key, app_value)
VALUES ('db.version', 'V1__init_app_info');
