-- V2__pack_release_checklist.sql

CREATE TABLE IF NOT EXISTS pack (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ru             VARCHAR(255) NOT NULL,
    name_en             VARCHAR(255),
    type                VARCHAR(50)  NOT NULL,
    status              VARCHAR(50)  NOT NULL,
    poses_count         INTEGER,
    couple_poses_count  INTEGER,
    tags                VARCHAR(512),
    description         VARCHAR(2048),
    source_dir          VARCHAR(1024),
    screens_dir         VARCHAR(1024),
    cover_file          VARCHAR(1024),
    package_file        VARCHAR(1024),
    created_at          TIMESTAMP WITH TIME ZONE,
    updated_at          TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS release (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id             BIGINT       NOT NULL,
    release_date_time   TIMESTAMP    NOT NULL,
    telegram_planned    BOOLEAN      NOT NULL,
    vk_planned          BOOLEAN      NOT NULL,
    boosty_planned      BOOLEAN      NOT NULL,
    tumblr_planned      BOOLEAN      NOT NULL,
    CONSTRAINT fk_release_pack
        FOREIGN KEY (pack_id) REFERENCES pack (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS checklist_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id        BIGINT       NOT NULL,
    title          VARCHAR(255) NOT NULL,
    done           BOOLEAN      NOT NULL,
    order_index    INTEGER      NOT NULL,
    CONSTRAINT fk_checklist_item_pack
        FOREIGN KEY (pack_id) REFERENCES pack (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_release_date_time
    ON release (release_date_time);

CREATE INDEX IF NOT EXISTS idx_checklist_item_pack_id
    ON checklist_item (pack_id);
